# Usar imagem base do Python
FROM python:3.12-slim
# Definir diretório de trabalho
WORKDIR /app


COPY . /app

# Expor a porta do servidor
EXPOSE 61624

#ENV PYTHONUNBUFFERED=1
# Definir o comando para rodar o servidor
CMD ["python3", "Servidor.py"]   